version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13.13.0

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run: make install
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: /hom/circleci/project
      - run: make build
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - build

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
